export const GET_USER_DATA = 'GET_USER_DATA';
export const GET_DASHBOARD_DATA = 'GET_DASHBOARD_DATA';
export const GET_DASHBOARD_PROJECTS = 'GET_DASHBOARD_PROJECTS';
export const GET_STATS = 'GET_STATS';
